import type { Table } from '../src/types/Table.type'

export const mockTables = (): Table[] => [
	{
		active: true,
		id: 1,
		index: 1,
		name: 'Test Table 1',
		locked_at: null,
		locked_by: null,
		seat_1: 'Test Person 1.1',
		seat_2: 'Test Person 1.2',
		seat_3: 'Test Person 1.3',
		seat_4: 'Test Person 1.4',
		seat_5: 'Test Person 1.5',
		seat_6: 'Test Person 1.6',
		seat_7: 'Test Person 1.7',
		seat_8: 'Test Person 1.8',
		seats: 8,
	},
	{
		active: true,
		id: 2,
		index: 2,
		name: 'Test Table 2',
		locked_at: null,
		locked_by: null,
		seat_1: 'Test Person 2.1',
		seat_2: 'Test Person 2.2',
		seat_3: '',
		seat_4: '',
		seat_5: '',
		seat_6: '',
		seat_7: '',
		seat_8: '',
		seats: 7,
	},
	{
		active: true,
		id: 3,
		index: 3,
		name: 'Test Table 3',
		locked_at: null,
		locked_by: null,
		seat_1: '',
		seat_2: '',
		seat_3: '',
		seat_4: '',
		seat_5: '',
		seat_6: '',
		seat_7: '',
		seat_8: '',
		seats: 4,
	},
]
