import type { TableDoc } from '../src/types/TableDoc.type'

export const mockTables = (): TableDoc[] => [
	{
		active: true,
		id: 'test_table_id-1',
		index: 1,
		name: 'Test Table 1',
		modified: { seconds: 0, nanoseconds: 0 },
		seat_1: 'Table 1, Test Person 1.1',
		seat_2: 'Table 1, Test Person 1.2',
		seat_3: 'Table 1, Test Person 1.3',
		seat_4: 'Table 1, Test Person 1.4',
		seat_5: 'Table 1, Test Person 1.5',
		seat_6: 'Table 1, Test Person 1.6',
		seat_7: 'Table 1, Test Person 1.7',
		seat_8: 'Table 1, Test Person 1.8',
		seats: 8,
	},
	{
		active: true,
		id: 'test_table_id-2',
		index: 2,
		name: 'Test Table 2',
		modified: { seconds: 0, nanoseconds: 0 },
		seat_1: 'Table 2, Test Person 2.1',
		seat_2: 'Table 2, Test Person 2.2',
		seat_3: '',
		seat_4: '',
		seat_5: '',
		seat_6: '',
		seat_7: '',
		seat_8: '',
		seats: 7,
	},
	{
		active: true,
		id: 'test_table_id-3',
		index: 3,
		name: 'Test Table 3',
		modified: { seconds: 0, nanoseconds: 0 },
		seat_1: '',
		seat_2: '',
		seat_3: '',
		seat_4: '',
		seat_5: '',
		seat_6: '',
		seat_7: '',
		seat_8: '',
		seats: 4,
	},
]
